#!/usr/bin/env ruby
# frozen_string_literal: true

require 'lambda_ruby_bundler'

options = LambdaRubyBundler::CLI::OptionParser.new.parse!(ARGV)

runner = if options[:cache_dir]
           LambdaRubyBundler::CLI::CacheRunner.new(
             options[:root_path], options[:app_path], options[:cache_dir]
           )
         else
           LambdaRubyBundler::CLI::StandardRunner.new(
             options[:root_path],
             options[:app_path],
             options[:build_dependencies],
             application_bundle: options[:output_path],
             dependency_layer: options[:dependencies_path]
           )
         end

puts runner.run.to_json
